// src/constants.js  —  Powertronics
// Generated by SolarFlow Client Form · 23 July 2026 at 13:00
// CRN prefix: PT 25-26=

import {
    FileText, FileCheck, FileUp, Globe, Landmark, Users, UserCheck, Sun, Package, Clock, Hammer, Zap, Wrench, ClipboardCheck, Gauge, Coins, Banknote, IndianRupee, CreditCard, AlertCircle,
} from 'lucide-react';

export const PRIMARY_STAGES = [
    { id: 'REGISTRATION PENDING', label: 'Registration Pending', icon: FileText },
    { id: 'REGISTRATION DONE', label: 'Registration Done', icon: FileCheck },
    { id: 'DOCUMENTS PENDING', label: 'Documents Pending', icon: FileUp },
    { id: 'PORTAL STEPS PENDING', label: 'Portal Steps Pending', icon: Globe },
    { id: 'LOAN PROCESS PENDING', label: 'Loan Process Pending', icon: Landmark },
    { id: 'VENDOR SELECTION PENDING', label: 'Vendor Selection Pending', icon: Users },
    { id: 'PT VENDOR SELECTED', label: 'Pt Vendor Selected', icon: UserCheck },
    { id: 'DCR PENDING', label: 'Dcr Pending', icon: Sun },
    { id: 'PANEL PENDING', label: 'Panel Pending', icon: Package },
    { id: 'INSTALLATION PENDING', label: 'Installation Pending', icon: Clock },
    { id: 'FABRICATION COMPLETED', label: 'Fabrication Completed', icon: Hammer },
    { id: 'WIRING COMPLETED', label: 'Wiring Completed', icon: Zap },
    { id: 'INSTALLATION COMPLETED', label: 'Installation Completed', icon: Wrench },
    { id: 'MGVCL APPROVAL PENDING', label: 'Mgvcl Approval Pending', icon: ClipboardCheck },
    { id: 'MGVCL METER PENDING', label: 'Mgvcl Meter Pending', icon: Gauge },
    { id: 'SUBSIDY REDEEM PENDING', label: 'Subsidy Redeem Pending', icon: Coins },
    { id: 'SUBSIDY REDEEMED', label: 'Subsidy Redeemed', icon: Banknote },
    { id: 'SUBSIDY AMOUNT DISBURSED', label: 'Subsidy Amount Disbursed', icon: IndianRupee },
];

// ─── Financial Tags (customise as needed) ────────────────────────────────────
export const FINANCIAL_TAGS = [
    // General Project options
    { id: 'Initial',                                  label: 'Initial',                                  icon: IndianRupee },
    { id: 'Installation',                              label: 'Installation',                              icon: IndianRupee },
    { id: 'Final payment',                             label: 'Final payment',                             icon: IndianRupee },

    // PM Surya Ghar options
    { id: 'Registration payment 20k',                 label: 'Registration payment 20k',                 icon: IndianRupee },
    { id: 'Installation payment',                      label: 'Installation payment',                      icon: IndianRupee },
    { id: 'Quotation amount',                          label: 'Quotation amount',                          icon: IndianRupee },
    { id: 'Final payment after meter installation',   label: 'Final payment after meter installation',   icon: IndianRupee },

];

export const FINANCIAL_TAG_COLORS = {
    'Initial':                                 { bg: 'bg-blue-50',     text: 'text-blue-700',     border: 'border-blue-200',     dot: 'bg-blue-400' },
    'Installation':                            { bg: 'bg-purple-50',   text: 'text-purple-700',   border: 'border-purple-200',   dot: 'bg-purple-400' },
    'Final payment':                           { bg: 'bg-emerald-50',  text: 'text-emerald-700',  border: 'border-emerald-200',  dot: 'bg-emerald-400' },

    'Registration payment 20k':                { bg: 'bg-blue-50',     text: 'text-blue-700',     border: 'border-blue-200',     dot: 'bg-blue-400' },
    'Installation payment':                    { bg: 'bg-purple-50',   text: 'text-purple-700',   border: 'border-purple-200',   dot: 'bg-purple-400' },
    'Quotation amount':                        { bg: 'bg-indigo-50',   text: 'text-indigo-700',   border: 'border-indigo-200',   dot: 'bg-indigo-400' },
    'Final payment after meter installation':  { bg: 'bg-emerald-50',  text: 'text-emerald-700',  border: 'border-emerald-200',  dot: 'bg-emerald-400' },
};

// Supabase metadata table categories (one per managed dropdown)
export const META_CATEGORIES = ['panel', 'inverter', 'meter_phase', 'payment_method'];

export const APP_ROLES = [
    { id: 'admin', label: 'Admin', user_type: 'admin', role: 'Admin' },
    { id: 'office', label: 'Office', user_type: 'sales', role: 'Office' },
    { id: 'channel_partner', label: 'Channel Partners', user_type: 'agent', role: 'Channel Partners' },
];
