// src/models.jsx  —  Powertronics
// Generated by SolarFlow Client Form · 23 July 2026 at 13:00
// Edit DEFAULT_PROJECT_CHECKLIST to match your actual workflow steps.

export const DEFAULT_PROJECT_CHECKLIST = [
    // ── Add your checklist steps here ─────────────────────────────────────────
    // Format: { id: 'unique_id', label: 'Step label', section: 'Section Name', checked: false }
    { id: 'step_1', label: 'Initial Registration Complete',  section: 'Registration', checked: false },
    { id: 'step_2', label: 'Documents Submitted',            section: 'Registration', checked: false },
    { id: 'step_3', label: 'Installation Done',              section: 'Installation', checked: false },
    { id: 'step_4', label: 'Meter Installed',                section: 'Post-Install', checked: false },
    { id: 'step_5', label: 'Subsidy Claimed',                section: 'Post-Install', checked: false },
    { id: 'step_6', label: 'Final Payment Cleared',          section: 'Post-Install', checked: false },
];

export function normalizeChecklist(rawChecklist) {
    let stored = [];
    if (Array.isArray(rawChecklist)) stored = rawChecklist;
    else if (typeof rawChecklist === 'string') {
        try { const p = JSON.parse(rawChecklist); if (Array.isArray(p)) stored = p; } catch {}
    }
    const byId = Object.fromEntries(stored.map(i => [i.id, i]));
    const merged = DEFAULT_PROJECT_CHECKLIST.map(i => ({
        ...i, ...byId[i.id],
        checked: byId[i.id]?.checked || false,
        checkedAt: byId[i.id]?.checkedAt || null,
        checkedBy: byId[i.id]?.checkedBy || null,
    }));
    const extra = stored.filter(i => !DEFAULT_PROJECT_CHECKLIST.some(d => d.id === i.id));
    return [...merged, ...extra];
}

export const DEFAULT_LEAD_FORM = {
    customer_name: '',
    phone_number: '',
    full_installation_address: '',
    area: '',
    google_drive_docs_link: '',
    google_maps_location_link: '',
    system_capacity_kwp: '',
    application_no: '',
    panel: '',
    inverter: '',
    date_of_registration: '',
    meter_phase: '',
    file_given_to_customer: '',
    meter_file_submission: '',
    meter_instaled: '',
    panel_and_inverter: '',
    fabrication_and_wiring: '',
    quoted_amount: '',
    stage: 'REGISTRATION PENDING',
};
