// src/models.jsx  —  Powertronics
// Generated by SolarFlow Client Form · 23 July 2026 at 13:00
// Edit DEFAULT_PROJECT_CHECKLIST to match your actual workflow steps.

// src/models.jsx

export const DEFAULT_PROJECT_CHECKLIST = [
    { id: 'file_ready_to_customer', label: 'File Ready to Customer', section: 'Project Checklist' },
    { id: 'file_given_to_customer', label: 'File Given to Customer', section: 'Project Checklist' },
    { id: 'meter_file_submission', label: 'Meter File Submission', section: 'Project Checklist' },
    { id: 'meter_instaled', label: 'Meter Installed', section: 'Project Checklist' },
    { id: 'panel_and_inverter', label: 'Panel and Inverter', section: 'Project Checklist' },
    { id: 'fabrication_and_wiring', label: 'Fabrication and Wiring', section: 'Project Checklist' },
];

/**
 * Normalizes data from flat database columns into the checklist format
 * Supports both signatures: 
 * 1. normalizeChecklist(customerObj)
 * 2. normalizeChecklist(rawChecklist, customerObj)
 */
export function normalizeChecklist(rawChecklist, customer = {}) {
    let projectRow = customer;
    let listSource = rawChecklist;

    // Detect if first argument is the entire customer/project row object
    if (rawChecklist && !Array.isArray(rawChecklist) && typeof rawChecklist === 'object') {
        projectRow = rawChecklist;
        listSource = rawChecklist.project_checklist;
    }

    let stored = [];
    if (Array.isArray(listSource)) {
        stored = listSource;
    } else if (typeof listSource === 'string') {
        try { const p = JSON.parse(listSource); if (Array.isArray(p)) stored = p; } catch {}
    }

    const byId = Object.fromEntries(stored.map(i => [i.id, i]));
    const normalizedDefault = DEFAULT_PROJECT_CHECKLIST.map(item => {
        const colValue = projectRow ? projectRow[item.id] : undefined;
        const hasDirectCol = colValue !== undefined && colValue !== null && colValue !== '';
        
        const isChecked = hasDirectCol
            ? (colValue === true || colValue === 'true' || colValue === 1 || colValue === 'Yes')
            : (byId[item.id]?.checked || false);

        let remarkVal = byId[item.id]?.remark || '';
        if (projectRow) {
            if (item.id === 'panel_and_inverter' && projectRow.panel_and_inverter_remarks !== undefined) {
                remarkVal = projectRow.panel_and_inverter_remarks || '';
            } else if (item.id === 'fabrication_and_wiring' && projectRow.fabrication_and_wiring_remarks !== undefined) {
                remarkVal = projectRow.fabrication_and_wiring_remarks || '';
            }
        }

        const checkedAt = byId[item.id]?.checkedAt || null;
        const checkedBy = byId[item.id]?.checkedBy || null;

        return {
            ...item,
            ...byId[item.id],
            checked: isChecked,
            remark: remarkVal,
            checkedAt,
            checkedBy,
        };
    });

    const defaultIds = new Set(DEFAULT_PROJECT_CHECKLIST.map(d => d.id));
    const customItems = stored.filter(i => i && i.id && !defaultIds.has(i.id));

    return [...normalizedDefault, ...customItems];
}

export const DEFAULT_LEAD_FORM = {
    customer_name: '',
    phone_number: '',
    full_installation_address: '',
    area: '',
    system_capacity_kwp: '',
    application_no: '',
    panel: '',
    inverter: '',
    date_of_registration: '',
    meter_phase: '',
    file_ready_to_customer: '',
    file_given_to_customer: '',
    meter_file_submission: '',
    meter_instaled: '',
    panel_and_inverter: '',
    fabrication_and_wiring: '',
    quoted_amount_3: '',
    po_no: '',
    bill_no: '',
    date: '',
    stage: 'REGISTRATION PENDING',
};
